export const courseDataArray = [
  {
    image: "/img/course/card-img.jpg",
    rating: 5.0,
    reviews: 76,
    isSuperhost: true,
    title: "Animasi 3D For Beginners - Become Animator Expert",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    price: 4000000,
    oldPrice: 5000000,
    duration: "20 min 10 sec",
    level: "Expert",
    modules: "6 Modules",
  },
  {
    image: "/img/course/card-img.jpg",
    rating: 5.0,
    reviews: 76,
    isSuperhost: true,
    title: "Animasi 3D For Beginners - Become Animator Expert",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    price: 4000000,
    oldPrice: 5000000,
    duration: "20 min 10 sec",
    level: "Expert",
    modules: "6 Modules",
  },
  {
    image: "/img/course/card-img.jpg",
    rating: 5.0,
    reviews: 76,
    isSuperhost: true,
    title: "Animasi 3D For Beginners - Become Animator Expert",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    price: 4000000,
    oldPrice: 5000000,
    duration: "20 min 10 sec",
    level: "Expert",
    modules: "6 Modules",
  },
  {
    image: "/img/course/card-img.jpg",
    rating: 5.0,
    reviews: 76,
    isSuperhost: true,
    title: "Animasi 3D For Beginners - Become Animator Expert",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    price: 4000000,
    oldPrice: 5000000,
    duration: "20 min 10 sec",
    level: "Expert",
    modules: "6 Modules",
  },
  {
    image: "/img/course/card-img.jpg",
    rating: 5.0,
    reviews: 76,
    isSuperhost: true,
    title: "Animasi 3D For Beginners - Become Animator Expert",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    price: 4000000,
    oldPrice: 5000000,
    duration: "20 min 10 sec",
    level: "Expert",
    modules: "6 Modules",
  },
  {
    image: "/img/course/card-img.jpg",
    rating: 5.0,
    reviews: 76,
    isSuperhost: true,
    title: "Animasi 3D For Beginners - Become Animator Expert",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    price: 4000000,
    oldPrice: 5000000,
    duration: "20 min 10 sec",
    level: "Expert",
    modules: "6 Modules",
  },
  {
    image: "/img/course/card-img.jpg",
    rating: 5.0,
    reviews: 76,
    isSuperhost: true,
    title: "Animasi 3D For Beginners - Become Animator Expert",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    price: 4000000,
    oldPrice: 5000000,
    duration: "20 min 10 sec",
    level: "Expert",
    modules: "6 Modules",
  }
  ];
