import { registerCustomizations } from "@/backoffice/components/global-customization/globalCustomizations";
import { DetailStudentProps } from "./listStudent.type";

export const ListStudentData: DetailStudentProps[] = [
  {
    id: '3mxta23p85k5oc4c',
    photo: '/icons/sintia-pic.svg',
    name: 'Cintia',
    email: 'cintia@gmail.com',
    noHp: '081876564328',
    createdAt: new Date(),
    updatedAt: new Date(),
    nik: '000788896554',
    school: 'SMKN 4 Malang',
    placeOfBirth: 'Malang',
    dateOfBirth: '31 Februari 2023',
    religion: 'Islam',
    gender: 'Female',
    province: 'East Java',
    city: 'Malang',
    subDistrict: 'Sukun',
    zipCode: '06549',
    addressKTP: 'Jl. Lorem Ipsum No 23',
    addressDomicile: 'Jl. Lorem Ipsum No 23',
    institutionName: 'SMKN 4 Malang',
    academicLevel: 'SMA/SMK Sederajat',
    startFrom: '16 Juni 2021',
    endDate: '19 Mei 2024',
  },
  {
    id: '3442x9iqptkepd4m',
    photo: '/images/photo-profile.png',
    name: 'Roby',
    email: 'roby@gmail.com',
    noHp: '089765676543',
    createdAt: new Date(),
    updatedAt: new Date(),
    nik: '', // Missing properties, consider filling them if available
    school: '',
    placeOfBirth: '',
    dateOfBirth: '',
    religion: '',
    gender: '',
    province: '',
    city: '',
    subDistrict: '',
    zipCode: '',
    addressKTP: '',
    addressDomicile: '',
    institutionName: '',
    academicLevel: '',
    startFrom: '',
    endDate: '',
  },
  {
    id: '123o89t3a1luomd6',
    photo: '/images/photo-profile.png',
    name: 'Jennifer',
    email: 'jennifer@gmail.com',
    noHp: '082345678765',
    createdAt: new Date(),
    updatedAt: new Date(),
    nik: '', // Missing properties
    school: '',
    placeOfBirth: '',
    dateOfBirth: '',
    religion: '',
    gender: '',
    province: '',
    city: '',
    subDistrict: '',
    zipCode: '',
    addressKTP: '',
    addressDomicile: '',
    institutionName: '',
    academicLevel: '',
    startFrom: '',
    endDate: '',
  },
  {
    id: 'do2ibr3oyicu0xfa',
    photo: '/images/photo-profile.png',
    name: 'Anton',
    email: 'anton@gmail.com',
    noHp: '082345678765',
    createdAt: new Date(),
    updatedAt: new Date(),
    nik: '', // Missing properties
    school: '',
    placeOfBirth: '',
    dateOfBirth: '',
    religion: '',
    gender: '',
    province: '',
    city: '',
    subDistrict: '',
    zipCode: '',
    addressKTP: '',
    addressDomicile: '',
    institutionName: '',
    academicLevel: '',
    startFrom: '',
    endDate: '',
  },
  {
    id: '1ug8cyd0xasuv1ui',
    photo: '/images/photo-profile.png',
    name: 'Catur',
    email: 'catur@gmail.com',
    noHp: '082345678765',
    createdAt: new Date(),
    updatedAt: new Date(),
    nik: '', // Missing properties
    school: '',
    placeOfBirth: '',
    dateOfBirth: '',
    religion: '',
    gender: '',
    province: '',
    city: '',
    subDistrict: '',
    zipCode: '',
    addressKTP: '',
    addressDomicile: '',
    institutionName: '',
    academicLevel: '',
    startFrom: '',
    endDate: '',
  },
];

const programCustomTitles: { [key: string]: string } = {};
const programCustomBreadcrumbs: { [key: string]: string } = {};

ListStudentData.forEach((student) => {
  programCustomTitles[student.id] = 'Detail Siswa';
  programCustomBreadcrumbs[student.id] = 'Detail Siswa';
});

registerCustomizations('program', programCustomTitles, programCustomBreadcrumbs);
