import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import clsx from 'clsx';
import { ThemeModeScript } from 'flowbite-react/components/ThemeModeScript';

import 'flatpickr/dist/flatpickr.css';
import 'react-quill/dist/quill.core.css';
import 'react-quill/dist/quill.snow.css';
import './globals.css';
import 'swiper/css';
import 'swiper/css/bundle';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Talentnesia',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <head>
        <ThemeModeScript />
      </head>
      <body suppressHydrationWarning={true} className={clsx(inter.className)}>
        {children}
      </body>
    </html>
  );
}
