export const holidays = [
  { day: 1, month: 1, name: "Tahun Baru" }, 
  { day: 25, month: 12, name: "Natal" }, 
  { day: 17, month: 8, name: "Hari Kemerdekaan" }, 
  { day: 1, month: 5, name: "Hari Buruh" }, 
  { day: 2, month: 5, name: "Hari Pendidikan Nasional" }, 
  { day: 28, month: 10, name: "Sumpah Pemuda" }, 
  { day: 10, month: 11, name: "Hari Pahlawan" }, 
  { day: 1, month: 6, name: "Hari Lahir Pancasila" }, 
  { day: 24, month: 12, name: "Hari Raya Natal" }, 
  { day: 20, month: 7, name: "Hari Raya Idul Adha" }, 
  { day: 21, month: 4, name: "Hari Kartini" },
  { day: 25, month: 4, name: "Hari Kemenangan" }, 
  { day: 1, month: 3, name: "Hari Raya Nyepi" }, 
  { day: 1, month: 7, name: "Hari Bhakti Adhyaksa" }, 
  { day: 11, month: 12, name: "Hari Nusantara" }, 
];
