export const accordionData = [
    {
      title: 'UX Design Principles',
      totalMinuteDuration: 120,
      totalCurriculum: 5,
      contents: [
        {
          id: 1,
          title: 'UX Introduction',
          duration: '10 min',
          type: '1',
          date: new Date('2024-08-28T23:00:00'), // Tanggal penyelesaian
          durationMinute: 10,
          status: 'completed', // Task selesai
          completed: true,
        },
        {
          id: 2,
          title: 'Jacobs Law',
          duration: '10 min',
          type: '1',
          date: new Date('2024-08-28T23:00:00'), // Tanggal penyelesaian
          durationMinute: 10,
          status: 'completed', // Task selesai
          completed: true,
        },
        {
          id: 3,
          title: 'Consistency Design',
          duration: '10 min',
          type: '1',
          date: new Date('2024-08-28T23:00:00'), // Tanggal penyelesaian
          durationMinute: 10,
          status: 'completed', // Task selesai
          completed: true,
        },
        {
          id: 4,
          title: 'Hicks Law',
          duration: '10 min',
          type: '2',
          date: new Date('2024-08-28T23:59:00'), 
          durationMinute: 10,
          status: 'incomplete', 
          completed: false,
        },
        {
          id: 5,
          title: 'Exam Hicks Law',
          duration: '10 min',
          type: '4',
          date: new Date('2024-08-28T23:59:00'), 
          durationMinute: 10,
          status: 'incomplete', 
          completed: false,
        },
        {
          id: 6,
          title: 'Mentoring',
          duration: '10 min',
          type: '3',
          date: new Date('2024-08-28T23:59:00'), 
          durationMinute: 10,
          status: 'incomplete', 
          completed: false,
        },
        {
          id: 7,
          title: 'Magic Number Is 4',
          duration: '10 min',
          type: '5',
          date: new Date('2024-08-28T23:59:00'), 
          durationMinute: 10,
          status: 'incomplete', 
          completed: false,
        },
        {
          id: 8,
          title: 'Etical Design',
          duration: '10 min',
          type: '5',
          date: new Date('2024-08-28T23:59:00'), 
          durationMinute: 10,
          status: 'incomplete', 
          completed: false,
        },
      ],
    },
    {
      title: 'UI Introduction',
      totalMinuteDuration: 150,
      totalCurriculum: 4,
      contents: [
        {
          id: 9,
          title: 'UX Introduction',
          duration: '10 min',
          type: '1',
          date: new Date('2024-08-28T23:00:00'), // Tanggal penyelesaian
          durationMinute: 10,
          status: 'completed', // Task selesai
          completed: true,
        },
        {
          id: 10,
          title: 'Jacobs Law',
          duration: '10 min',
          type: '2',
          date: new Date('2024-08-28T23:00:00'), // Tanggal penyelesaian
          durationMinute: 10,
          status: 'completed', // Task selesai
          completed: true,
        },
        {
          id: 11,
          title: 'Consistency Design',
          duration: '10 min',
          type: '3',
          date: new Date('2024-08-28T23:59:00'), 
          durationMinute: 10,
          status: 'incomplete', 
          completed: false,
        },
        {
          id: 12,
          title: 'Hicks Law',
          duration: '10 min',
          type: '3',
          date: new Date('2024-08-28T23:59:00'), 
          durationMinute: 10,
          status: 'incomplete', 
          completed: false,
        },
        {
          id: 13,
          title: 'Exam Hicks Law',
          duration: '10 min',
          type: '4',
          date: new Date('2024-08-28T23:59:00'), 
          durationMinute: 10,
          status: 'incomplete', 
          completed: false,
        },
        {
          id: 14,
          title: 'Mentoring',
          duration: '10 min',
          type: '3',
          date: new Date('2024-08-28T23:59:00'), 
          durationMinute: 10,
          status: 'incomplete', 
          completed: false,
        },
        {
          id: 15,
          title: 'Magic Number Is 4',
          duration: '10 min',
          type: '5',
          date: new Date('2024-08-28T23:59:00'), 
          durationMinute: 10,
          status: 'incomplete', 
          completed: false,
        },
        {
          id: 16,
          title: 'Etical Design',
          duration: '10 min',
          type: '5',
          date: new Date('2024-08-28T23:59:00'), 
          durationMinute: 10,
          status: 'incomplete', 
          completed: false,
        },
      ],
    },
  ];
  