import { Article } from "./blog.type";

export const recentArticles: Article[] = [
    {
      title: "Using Notion To Make A Portfolio",
      author: "Prayuda Rians",
      date: "3 Jan 2023",
      views: 132,
      imageSrc: "/img/blog/writing.jpg",
    },
    {
        title: "Using Notion To Make Portfolio",
        author: "Prayuda Rians",
        date: "3 Jan 2023",
        views: 132,
        imageSrc: "/img/blog/writing.jpg",
      },
      {
        title: "Using Notion To Make Portfolio",
        author: "Prayuda Rians",
        date: "3 Jan 2023",
        views: 132,
        imageSrc: "/img/blog/writing.jpg",
      },
      {
        title: "Using Notion To Make Portfolio",
        author: "Prayuda Rians",
        date: "3 Jan 2023",
        views: 132,
        imageSrc: "/img/blog/writing.jpg",
      },
      {
        title: "Using Notion To Make Portfolio",
        author: "Prayuda Rians",
        date: "3 Jan 2023",
        views: 132,
        imageSrc: "/img/blog/writing.jpg",
      },
      {
        title: "Using Notion To Make A Portfolio",
        author: "Prayuda Rians",
        date: "3 Jan 2023",
        views: 132,
        imageSrc: "/img/blog/writing.jpg",
      },
      {
        title: "Using Notion To Make Portfolio",
        author: "Prayuda Rians",
        date: "3 Jan 2023",
        views: 132,
        imageSrc: "/img/blog/writing.jpg",
      },
      {
        title: "Using Notion To Make Portfolio",
        author: "Prayuda Rians",
        date: "3 Jan 2023",
        views: 132,
        imageSrc: "/img/blog/teacher.jpg",
      },
    {
      title: "Using Notion To Make Portfolio",
      author: "Prayuda Rians",
      date: "3 Jan 2023",
      views: 132,
      imageSrc: "/img/blog/writing.jpg",
    },
    {
        title: "Using Notion To Make Portfolio",
        author: "Prayuda Rians",
        date: "3 Jan 2023",
        views: 132,
        imageSrc: "/img/blog/writing.jpg",
      },
      {
        title: "Using Notion To Make Portfolio",
        author: "Prayuda Rians",
        date: "3 Jan 2023",
        views: 132,
        imageSrc: "/img/blog/writing.jpg",
      },
      {
        title: "Using Notion To Make Portfolio",
        author: "Prayuda Rians",
        date: "3 Jan 2023",
        views: 132,
        imageSrc: "/img/blog/writing.jpg",
      },
      {
        title: "Using Notion To Make Portfolio",
        author: "Prayuda Rians",
        date: "3 Jan 2023",
        views: 132,
        imageSrc: "/img/blog/writing.jpg",
      },
      {
        title: "Using Notion To Make Portfolio",
        author: "Prayuda Rians",
        date: "3 Jan 2023",
        views: 132,
        imageSrc: "/img/blog/writing.jpg",
      },
      {
        title: "Using Notion To Make Portfolio",
        author: "Prayuda Rians",
        date: "3 Jan 2023",
        views: 132,
        imageSrc: "/img/blog/writing.jpg",
      },
      {
        title: "Using Notion To Make Portfolio",
        author: "Prayuda Rians",
        date: "3 Jan 2023",
        views: 132,
        imageSrc: "/img/blog/teacher.jpg",
      },
  ];